\c shows;

INSERT INTO 
    shows(name, url, num_seasons, num_episodes, released_date, description, category, language, rating, is_favorite)
VALUES
    ('What I Like About You', 'https://m.media-amazon.com/images/M/MV5BM2MwMTRmNzktYTQ1ZS00MzEwLWIzZjctOGVhZWExYThmYmQ2XkEyXkFqcGdeQXVyMjczOTU2NTI@._V1_.jpg', 4, 86, '2002-09-20', 'When their dad took a job in Japan, livewire Holly Tyler was sent to her straight-laced sister, Valerie, and moved in together in New York City, turning Valerie''s life upside down.', 'TV Series', 'English', 5, true),
    ('The Simpsons','https://m.media-amazon.com/images/I/71+7X4Uw3OL._AC_SL1500_.jpg', 34, 750, '1989-12-17', 'The satiric adventures of a working-class family in Springfield city.', 'Animation series', 'English', 5, true),
    ('Fairy Tail', 'https://m.media-amazon.com/images/I/71ELYAMCiXS._AC_SL1500_.jpg', 9, 175, '2009-10-12', 'The story revolves around Natsu Dragneel, a Fire Dragon Slayer wizard, and his companions in the Fairy Tail Guild. As they work together, they take on various quests, battle formidable foes, and uncover the mysteries of their world.', 'Anime', 'Japanese', 5, true),
    ('Squid Game (오징어 게임)', 'https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg', 1, 9, '2021-10-12', 'Hundreds of cash-strapped players accept a strange invitation to compete in children''s games. Inside, a tempting prize awaits with deadly high stakes: a survival game that has a whopping 45.6 billion-won prize at stake.', 'survival tv series', 'Korean', 5, true),
    ('Crash Landing on You (사랑의 불시착)', 'https://m.media-amazon.com/images/M/MV5BMzRiZWUyN2YtNDI4YS00NTg2LTg0OTgtMGI2ZjU4ODQ4Yjk3XkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_.jpg', NULL, 16, '2019-12-14', 'Yoon Se-ri is a South Korean successful entrepreneur and a chaebol heiress. One day, while paragliding in Seoul, a tornado blows her off course. As a result, she crash-lands into the North Korean portion of the DMZ. Ri Jeong-hyeok is a member of the North Korean elite and a captain in the Korean People''s Army. As he is patrolling, he meets Se-ri and saves her. Having decided to help her go back to the South, he hides her from other North Koreans, especially Cho Cheol-gang who is out to expose him. As they spend time together, they fall in love while they strive to bridge the gap between their worlds.', 'Korean drama', 'Korean', 5, true),
    ('Falling Into Your Smile (你微笑时很美)', 'https://m.media-amazon.com/images/M/MV5BMzY3MDI0ZWEtZGRjYy00YWE0LWIzOWQtMzBjZDYwNTg1ZmExXkEyXkFqcGdeQXVyOTE4NzcwNzI@._V1_.jpg', NULL, 31, '2021-06-23', 'Student Tong Yao makes two vows: to never be in a relationship with someone in the same field and to make up for the Chinese League of Legends. When Tong Yao earns her spot as the first formal female player in China''s professional league, she catches the attention of an elite team captain. Facing doubts and inconveniences, she meets each challenge with her own persistence and her teammates'' support. After much effort, what will become of her vows? Will she stand on the world stage to make up for six years of regret? Will she avoid a romantic entanglement within the e-sports world? This drama is adapted from the novel called You''re Beautiful When You Smile (你微笑时很美) by Qing Mei.', 'Chinese drama', 'Chinese', 4, true),
    ('Love 020 (微微一笑很倾城)', 'https://m.media-amazon.com/images/M/MV5BNmMyYzAwOTctMjlkYi00ODlmLTk0MGQtOTBhZGRmMmFhMWIyXkEyXkFqcGdeQXVyNDIyMTI3MTM@._V1_FMjpg_UX1000_.jpg', NULL, 16, '2016-06-09', 'When a computer-science major gets dumped by her “husband” in an online role-playing game, she attracts a new proposal from the game''s top player.', 'Chinese drama', 'Chinese', 4, true),
    ('Friends', 'https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg', 10, 236, '1994-09-22', 'The merry misadventures of six 20-something to thirty year-old pals as they navigate the pitfalls of work, life and love in living in the Manhattan borough of New York City.', 'TV Series', 'English', 4, true),
    ('So I Married The Anti-fan (그래서 나는 안티팬과 결혼했다)', 'https://m.media-amazon.com/images/M/MV5BMzdkOGNiZmItYTQxZS00MTU0LWI0MzMtNDg4YjI0ZWY2ZGY2XkEyXkFqcGdeQXVyMTU2NjA2MzY@._V1_.jpg', NULL, 16, '2021-06-19', 'Hoo Joon is a top star and Geun Young is a magazine reporter who both attend a club’s opening night. There, Young witnesses Joon''s violent behavior and accidentally vomits on him. Young loses her job and is convinced that Joon has to be behind her firing. She retaliates by demonstrating in front of Joon''s management office, where her picketing eventually garners some media attention and the anti-fan label. A producer approaches her about participating in a reality TV show whose premise is that of a celebrity living with their anti-fan. Unemployed, she jumps at the opportunity. Meanwhile, Joon is offered the same show and accepts, thinking that it could only improve his image. When filming begins, Joon and Young try to give each other a hard time on set, only to fall head over heels for one another.', 'Korean drama', 'Korean', 3, true),
    ('Supernatural', 'https://de.web.img3.acsta.net/pictures/19/09/12/09/32/3713504.jpg', 15, 327, '2005-09-13', 'Two brothers follow their father''s footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.', 'TV Series', 'English', 1, true),
    ('Supernatural', 'https://de.web.img3.acsta.net/pictures/19/09/12/09/32/3713504.jpg', 15, 327, '2005-09-13', 'Two brothers follow their father''s footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.', 'TV Series', 'English', 1, true),
    ('Bob''s Burger', 'https://m.media-amazon.com/images/M/MV5BZGJiNmM1NDctNWUxYS00YzE4LWJjNTgtYTJhYzE0NjFmMTMwXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg', 13, 260, '2011-01-09', 'Bob Belcher runs his dream restaurant with his wife and three children as their last hope of holding the family together.', 'Animation Series', 'English', 1, true),
    ('The Big Bang Theory', 'https://m.media-amazon.com/images/M/MV5BY2FmZTY5YTktOWRlYy00NmIyLWE0ZmQtZDg2YjlmMzczZDZiXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_.jpg', 12, 278, '2007-09-24', 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.', 'TV Series', 'English', 3, true),
    ('Naruto: Shippuden', 'https://m.media-amazon.com/images/M/MV5BZGFiMWFhNDAtMzUyZS00NmQ2LTljNDYtMmZjNTc5MDUxMzViXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg', 22, 500, '2009-10-28', 'Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village''s leader and strongest ninja.', 'Anime', 'Japanese', 3, true),
    ('Full House', 'https://m.media-amazon.com/images/M/MV5BN2VhZjA4ZGMtMTM0ZC00MTIyLWFjMzMtOWI4Y2JjN2IyNmYyXkEyXkFqcGdeQXVyNjc4NTExMTk@._V1_.jpg', 8, 192, '1987-09-22', 'After the death of his wife Pam, sports anchor Danny Tanner recruits his brother-in-law (Pam''s younger brother) Jesse, a rock musician, and his best friend since childhood, Joey, who works as a stand-up comedian, to help raise his three young daughters in San Francisco—DJ, Stephanie and Michelle. Living under one roof, these friends experience the trials of parenthood along with their fair share of laughs and life lessons.', 'TV Series', 'English', 5, true),
    ('Fuller House', 'https://m.media-amazon.com/images/M/MV5BMjAxMzU5MzA0MF5BMl5BanBnXkFtZTgwODgyOTg1MzI@._V1_FMjpg_UX1000_.jpg', 5, 75, '2016-02-26', 'In a continuation of Full House (1987), D.J. Fuller is a mother of three young boys and is a recent widow. D.J.''s sister Stephanie, her best friend Kimmy and Kimmy''s teenage daughter all move in to help raise her sons. The house is now a lot fuller.', 'TV Series', 'English', 4, true),
    ('Reba', 'https://m.media-amazon.com/images/M/MV5BOWE1MDY2MjUtZGRmYy00MmNjLWI1MGEtNmI5ZmNlMzI3NmFhXkEyXkFqcGdeQXVyODQwNjgyMw@@._V1_.jpg', 6, 127, '2001-10-05', 'Set in the suburbs of North Houston, middle-aged wisecracking Reba Hart''s life is thrown upside down when she finds her husband of nearly 20 years has decided to divorce her after getting his dentist hygienist, Barbra Jean "BJ," who''s half Reba''s age, pregnant. Her life is thrown in a further whirlwind as her 17-year-old daughter is also pregnant by her high school football prodigy boyfriend, Van Montgomery, and has decided to get married. With all of the new chaos and dysfunction in her life, Reba attempts to get through her day.', 'TV Series', 'English', 4, true);
