\c shows;

INSERT INTO 
    shows(title, image_url, num_seasons, num_episodes, released_date, description, category, language, rating, is_favorite)
VALUES
    ('What I Like About You', 'https://www.imdb.com/title/tt0321018/mediaviewer/rm1911854593/?ref_=tt_ov_i', 4, 86, '2002-09-20', 'When their dad took a job in Japan, livewire Holly Tyler was sent to her straight-laced sister, Valerie, and moved in together in New York City, turning Valerie''s life upside down.', 'tv series', 'English', 5, true),
    ('The Simpsons','https://www.imdb.com/title/tt0096697/mediaviewer/rm1730745600/?ref_=tt_ov_i', 34, 750, '1989-12-17', 'The satiric adventures of a working-class family in Springfield city.', 'anime tv series', 'English', 5, true),
    ('Fairy Tail', 'https://www.imdb.com/title/tt1528406/mediaviewer/rm3430816512/?ref_=tt_ov_i', 9, 175, '2009-10-12', 'The story revolves around Natsu Dragneel, a Fire Dragon Slayer wizard, and his companions in the Fairy Tail Guild. As they work together, they take on various quests, battle formidable foes, and uncover the mysteries of their world.', 'anime series', 'Japanese', 5, true),
    ('Squid Game (오징어 게임)', 'https://www.imdb.com/title/tt10919420/mediaviewer/rm2766402049/?ref_=tt_ov_i', 1, 9, '2021-10-12', 'Hundreds of cash-strapped players accept a strange invitation to compete in children''s games. Inside, a tempting prize awaits with deadly high stakes: a survival game that has a whopping 45.6 billion-won prize at stake.', 'survival tv series', 'Korean', 5, true),
    ('Crash Landing on You (사랑의 불시착)', 'https://www.imdb.com/title/tt10850932/mediaviewer/rm3056777473/?ref_=tt_ov_i', NULL, 16, '2019-12-14', 'Yoon Se-ri is a South Korean successful entrepreneur and a chaebol heiress. One day, while paragliding in Seoul, a tornado blows her off course. As a result, she crash-lands into the North Korean portion of the DMZ. Ri Jeong-hyeok is a member of the North Korean elite and a captain in the Korean People''s Army. As he is patrolling, he meets Se-ri and saves her. Having decided to help her go back to the South, he hides her from other North Koreans, especially Cho Cheol-gang who is out to expose him. As they spend time together, they fall in love while they strive to bridge the gap between their worlds.', 'romanic-comedy Korean drama', 'Korean', 5, true),
    ('Falling Into Your Smile (你微笑时很美)', 'https://www.imdb.com/title/tt11290960/mediaviewer/rm134412801/?ref_=tt_ov_i', NULL, 31, '2021-06-23', 'Student Tong Yao makes two vows: to never be in a relationship with someone in the same field and to make up for the Chinese League of Legends. When Tong Yao earns her spot as the first formal female player in China''s professional league, she catches the attention of an elite team captain. Facing doubts and inconveniences, she meets each challenge with her own persistence and her teammates'' support. After much effort, what will become of her vows? Will she stand on the world stage to make up for six years of regret? Will she avoid a romantic entanglement within the e-sports world? This drama is adapted from the novel called You''re Beautiful When You Smile (你微笑时很美) by Qing Mei.', 'Chinese drama', 'Chinese', 4, true),
    ('Love 020 (微微一笑很倾城)', 'https://www.imdb.com/title/tt6055498/mediaviewer/rm2883060224/?ref_=tt_ov_i', NULL, 16, '2016-06-09', 'When a computer-science major gets dumped by her “husband” in an online role-playing game, she attracts a new proposal from the game''s top player.', 'Chinese drama', 'Chinese', 4, true);
